# Generated by Django 4.1.7 on 2023-03-07 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_account_created_at_alter_account_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 21, 42, 38, 184286), verbose_name='Account created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 21, 42, 38, 184320), verbose_name='Account updated'),
        ),
    ]
