# Generated by Django 4.1.7 on 2023-03-07 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_profile_company_address_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_desc',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 23, 2, 20, 495923), verbose_name='Account created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 23, 2, 20, 495959), verbose_name='Account updated'),
        ),
    ]
