# Generated by Django 4.1.7 on 2023-03-07 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_profile_company_desc_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 23, 19, 59, 795183), verbose_name='Account created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 23, 19, 59, 795217), verbose_name='Account updated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
