# Generated by Django 4.1.7 on 2023-03-08 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 17, 24, 52, 486487), verbose_name='Account created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 17, 24, 52, 486523), verbose_name='Account updated'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default=False, upload_to='profile_picture'),
        ),
    ]
