# Generated by Django 4.1.7 on 2023-03-09 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0014_alter_account_created_at_alter_account_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 6, 59, 28, 935395), verbose_name='Account created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 6, 59, 28, 935453), verbose_name='Account updated'),
        ),
    ]
