# Generated by Django 4.1.7 on 2023-03-08 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_posts', '0004_remove_category_product_alter_product_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 17, 45, 55, 450675)),
        ),
    ]
