# Generated by Django 4.1.7 on 2023-03-08 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_posts', '0005_product_category_id_alter_product_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='review',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 17, 58, 29, 515228)),
        ),
    ]
