# Generated by Django 4.1.7 on 2023-03-09 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_posts', '0007_alter_product_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 6, 59, 29, 24219)),
        ),
    ]
